targets:
  $default:
    builders:
      build_web_compilers:entrypoint:
        generate_for:
        - test/**.dart
        - lib/**.dart
        options:
          compilers:
            dartdevc:
              args:

            dart2js:
              args:
              
            dart2wasm:
              args:
              
        dev_options:
          compilers:
            dartdevc:
              args:
            
        release_options:
          compilers:
            dart2js:
              args:

            dart2wasm:
              args:
