dependencies:
  ansicolor: ^2.0.3
  args: ^2.4.2
  async: ^2.11.0
  browser_launcher: ^1.1.1
  characters: ^1.3.0
  cli_config: ^0.2.0
  cli_util: ^0.4.1
  collection: ^1.19.0
  convert: ^3.1.1
  crypto: ^3.0.3
  csslib: ^1.0.0
  file: ^7.0.0
  glob: ^2.1.2
  http: ^1.2.2
  http2: ^2.3.0
  http_multi_server: ^3.2.1
  http_parser: ^4.1.0
  intl: ^0.19.0
  intl_translation: ^0.20.0
  io: ^1.0.4
  json_rpc_2: ^3.0.2
  json_serializable: ^6.8.0
  logging: ^1.2.0
  markdown: ^7.2.2
  path: ^1.9.0
  platform: ^3.1.5
  pool: ^1.5.1
  shelf: ^1.4.2
  shelf_proxy: ^1.0.4
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  shelf_web_socket: ^2.0.0
  stack_trace: ^1.11.1
  term_glyph: ^1.2.1
  web: ^1.0.0
  web_socket_channel: ^3.0.1


description: "Open Source Mathematics Engine"

dev_dependencies:
  build_runner: ^2.4.12
  build_web_compilers: ^4.0.11
  lints: ^4.0.0
  shelf_test_handler: ^2.0.2
  test: ^1.25.8

environment:
  sdk: '>=3.0.0 <=6.0.0'

name: hyaena_technologies
version: 0.2.0